# Generated by Django 4.1.3 on 2022-12-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receita',
            name='rendimento',
            field=models.CharField(max_length=100),
        ),
    ]
